// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import "fyne.io/fyne/v2"

var resourceConfigYml = &fyne.StaticResource{
	StaticName: "config.yml",
	StaticContent: []byte(
		"bossid: hsiehpj\r\nassid: yenju0115\r\nasspwd: 110803Ben\r\nOS: mac\r\nmember:\r\n    - 彥茹\r\n    - 家毓\r\n    - 昀潔\r\n    - 宇安\r\n    - 昀安\r\n    - 宇昕\r\n    - 林懿\r\n    - 永一\r\n    - 品程\r\n    - 紹閔\r\n    - Yaron\r\n"),
}
